version: '3'

services:
  otrs:
    image: juanluisbaptiste/otrs:latest
    ports:
    - "80:80"
  # If running behind a proxy container, expose the ports instead
  # and link the proxy container to this one.
  #  expose:
  #  - "80"
    links:
    - mariadb:mariadb
    - postfix:postfix
  # You should use env_file: instead of environment: for your environment
  # variables. Look at the README.md file for a list of available variables.
    env_file: .env
  mariadb:
    image: juanluisbaptiste/otrs-mariadb:latest
    expose:
    - "3306"
    env_file: .env
