apiVersion: v1
kind: Pod
metadata:
  name: otrspod
spec:
  containers:
    - name: otrs
      image: juanluisbaptiste/otrs:latest
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: Nogger123
      - name: MYSQL_ROOT_USER
        value: root
      - name: OTRS_DB_HOST
        value: mariadb
      - name: OTRS_DB_NAME
        value: otrs
      - name: OTRS_DB_PASSWORD
        value: Nogger123
      - name: OTRS_DB_PORT
        value: "3306"
      - name: OTRS_DB_USER
        value: otrs
      - name: OTRS_ROOT_PASSWORD
        value: Nogger123
#      - name: OTRS_INSTALL
#        value: "yes"
      volumeMounts:
      - mountPath: "/opt/otrs/Kernel"
        name: otrspd
  volumes:
    - name: otrspd
      persistentVolumeClaim:
        claimName: pvc-otrs
#DB-t bele és ZSAAAAAAAAAAAAAAAAAAAAAa
