apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
  creationTimestamp: "2020-07-23T09:13:40Z"
  generation: 1
  managedFields:
  - apiVersion: networking.istio.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:gateways: {}
        f:hosts: {}
        f:http: {}
    manager: kubectl
    operation: Create
    time: "2020-07-23T09:13:40Z"
  name: otrs-2
  namespace: otrs-2
  resourceVersion: "85956653"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/otrs-2/virtualservices/otrs
  uid: 712c83a4-e3d2-4d59-8030-e2c12236b1dd
spec:
  gateways:
  - istio-system/default-gateway
  hosts:
  - otrs-2.k8s.icellmobilsoft.hu
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: otrs
        port:
          number: 80
