apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-prod.yml -o helmkompose
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postfix
  name: postfix
spec:
  ports:
  - name: "25"
    port: 25
    targetPort: 25
  selector:
    io.kompose.service: postfix
status:
  loadBalancer: {}
