apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prod.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: env
        - name: MYSQL_ROOT_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_USER
              name: env
        - name: OTRS_BACKUP_TIME
          valueFrom:
            configMapKeyRef:
              key: OTRS_BACKUP_TIME
              name: env
        - name: OTRS_BACKUP_TYPE
          valueFrom:
            configMapKeyRef:
              key: OTRS_BACKUP_TYPE
              name: env
        - name: OTRS_DB_HOST
          valueFrom:
            configMapKeyRef:
              key: OTRS_DB_HOST
              name: env
        - name: OTRS_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: OTRS_DB_NAME
              name: env
        - name: OTRS_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: OTRS_DB_PASSWORD
              name: env
        - name: OTRS_DB_PORT
          valueFrom:
            configMapKeyRef:
              key: OTRS_DB_PORT
              name: env
        - name: OTRS_DB_USER
          valueFrom:
            configMapKeyRef:
              key: OTRS_DB_USER
              name: env
        - name: OTRS_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: OTRS_ROOT_PASSWORD
              name: env
        image: juanluisbaptiste/otrs-mariadb:latest
        imagePullPolicy: ""
        name: mariadb
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-claim0
        - mountPath: /etc/localtime
          name: tz-config
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mariadb-claim0
        persistentVolumeClaim:
          claimName: mariadb-claim0
      - hostPath:
          path: /etc/localtime
        name: tz-config
status: {}
